import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {neutralPoseRad,segmentTransforms} from './fly-fk.js';
export const SEATS=[[.5,.14],[.89,.4],[.74,.77],[.26,.77],[.11,.4]];
export const COLORS=['#ff9379','#78d9fa','#eacc76','#caa0ff','#7ed9b3'];
export async function createFlyTable(container,onFrame){
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0x000000,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;renderer.autoClear=false;container.prepend(renderer.domElement);renderer.domElement.className='fly-canvas';renderer.domElement.setAttribute('aria-label','Five animated 3D fruit flies playing Dou Dizhu');renderer.domElement.setAttribute('role','img');
 const [asset,rig,gait]=await Promise.all([new GLTFLoader().loadAsync('/assets/neuromechfly.glb'),fetch('/assets/fly-rig.json').then(r=>r.json()),fetch('/assets/walk-gait.json').then(r=>r.json())]);
 const neutral={...neutralPoseRad(rig),...gait.standingPose},camera=new THREE.PerspectiveCamera(34,1,.1,60);camera.position.set(4.7,5.3,7);camera.lookAt(0,.5,0);
 const players=COLORS.map((color,i)=>{const scene=new THREE.Scene();scene.add(new THREE.HemisphereLight(0xfdf5de,0x455e62,2.4));const light=new THREE.DirectionalLight(0xffeaca,4);light.position.set(3,7,6);scene.add(light);const rim=new THREE.DirectionalLight(color,3.5);rim.position.set(-5,3,-4);scene.add(rim);const holder=new THREE.Group();scene.add(holder);const fly=asset.scene.clone(true);fly.scale.setScalar(.86);holder.add(fly);const segments=new Map();fly.traverse(o=>{if(rig.segments.includes(o.name))segments.set(o.name,o);});const disk=new THREE.Mesh(new THREE.CylinderGeometry(1.5,1.65,.25,48),new THREE.MeshStandardMaterial({color:0x383827,roughness:.65,metalness:.3}));disk.position.y=-.25;scene.add(disk);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.48,.055,8,64),new THREE.MeshBasicMaterial({color}));ring.rotation.x=-Math.PI/2;ring.position.y=-.1;scene.add(ring);
 const crown=new THREE.Group();for(let j=0;j<5;j++){const p=new THREE.Mesh(new THREE.ConeGeometry(.19,.55,4),new THREE.MeshStandardMaterial({color:0xffc83d,metalness:.7,roughness:.25}));p.position.set(Math.cos(j*Math.PI*2/5)*.43,.2,Math.sin(j*Math.PI*2/5)*.43);crown.add(p);}const base=new THREE.Mesh(new THREE.CylinderGeometry(.56,.48,.22,16),new THREE.MeshStandardMaterial({color:0xf0aa32,metalness:.65,roughness:.3}));crown.add(base);crown.position.set(.25,2.35,0);holder.add(crown);crown.visible=false;
 const halo=new THREE.Mesh(new THREE.TorusGeometry(1,.06,10,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:0}));halo.rotation.x=Math.PI/2;halo.position.set(0,1.7,0);holder.add(halo);return {scene,holder,segments,pose:{...neutral},crown,ring,halo};});
 let state=null,raf,disposed=false,lastFk=0;const start=performance.now();let width=0,height=0;
 const resize=()=>{width=container.clientWidth;height=container.clientHeight;renderer.setSize(width,height);};const ro=new ResizeObserver(resize);ro.observe(container);resize();
 function frame(){if(disposed)return;raf=requestAnimationFrame(frame);const time=(performance.now()-start)/1000;renderer.setScissorTest(false);renderer.clear();renderer.setScissorTest(true);const small=width<600,boxW=small?104:148,boxH=small?104:148;
  for(let i=0;i<5;i++){const p=players[i],active=state?.turn===i&&['play','bid'].includes(state.phase),winner=state?.match?.winningSeats?.includes(i)&&['settle','roundEnd','seasonEnd'].includes(state.phase),credit=state?.credit?.borrowers?.includes(i),positive=credit&&state.phase==='loanPositive',negative=credit&&state.phase==='loanNegative';p.holder.position.y=winner?Math.abs(Math.sin(time*5))*.5:negative?-.1:Math.sin(time*2+i)*.035;p.holder.rotation.y=Math.sin(time*.7+i)*.12+(i===1||i===2?-.4:.15);p.holder.rotation.z=negative?Math.sin(time*7)*.035:0;p.crown.visible=state?.match?.landlord===i;p.crown.rotation.y=time*.25;p.ring.material.color.set(negative?'#bc7cef':COLORS[i]);p.ring.scale.setScalar(active?1+Math.sin(time*5)*.07:1);p.halo.material.opacity=positive||negative||winner?.55+Math.sin(time*6)*.2:0;p.halo.material.color.set(negative?'#a780de':positive?'#ffdc69':COLORS[i]);p.halo.rotation.z=time;
  if(time-lastFk>1/24){Object.assign(p.pose,neutral);const index=Math.floor((time*(active?2:1)+i*.17)%1*96);if(active)for(const k in gait.frames[index])p.pose[k]=THREE.MathUtils.lerp(neutral[k]??0,gait.frames[index][k],.25);for(const d of rig.dofs){if(d.name.includes('pedicel')&&d.name.endsWith('yaw'))p.pose[d.name]+=Math.sin(time*4+i)*.15;if(winner||positive){if(d.name.includes('wing')&&d.name.endsWith('roll'))p.pose[d.name]=(d.name.includes('l_wing')?-1:1)*1.15;if(d.name.includes('wing')&&d.name.endsWith('pitch'))p.pose[d.name]+=.5*Math.sin(time*50);}}const transforms=segmentTransforms(rig,p.pose);for(const [name,m]of p.segments){m.matrix.set(...transforms[name]);m.matrixAutoUpdate=false;}}
  const [x,y]=SEATS[i];const px=x*width-boxW/2,py=height-y*height-boxH/2;renderer.setViewport(px,py,boxW,boxH);renderer.setScissor(px,py,boxW,boxH);renderer.render(p.scene,camera);
 }if(time-lastFk>1/24)lastFk=time;renderer.setScissorTest(false);onFrame?.(renderer.domElement);}
 frame();return {update(s){state=s;},canvas:renderer.domElement,dispose(){disposed=true;cancelAnimationFrame(raf);ro.disconnect();renderer.dispose();}};
}
