import './ddz-style.css';
import {rankOf as rank,cardSuit} from './doudizhu-rules.js';
import {createFlyTable,SEATS,COLORS} from './ddz-scene.js';
import {createBrainView} from './ddz-brain-view.js';
import {languages,t,locale,n,setLanguage,initLanguage} from './ddz-i18n.js';
const NAMES=['Iris','Cobalt','Mica','Ember','Jade'];
const app=document.getElementById('app');let neuralView=null,neuralSeat=0,followBrain=true,neuralCache=Array(5).fill(null),selectedNeuron=null;let state=null,scene=null,socket=null,reconnectTimer,selected=0,connected=false,retry=1000,lastActionAt=0,copy=null,muted=true,audioCtx,recording=null,lastMatches=-1;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const html=(id,v)=>{const e=document.getElementById(id);if(e&&e.innerHTML!==v)e.innerHTML=v;};
const text=(id,v)=>{const e=document.getElementById(id);if(e&&e.textContent!==String(v))e.textContent=v;};
const rankText=id=>({11:'J',12:'Q',13:'K',14:'A',15:'2',16:'☆',17:'★'}[rank(id)]||String(rank(id)));
const suit=id=>cardSuit(id)||'JOKER';
const card=(id,extra='')=>`<span class="card ${id%54>=52?'joker':''} ${['♥','♦'].includes(suit(id))||rank(id)===17?'red':''} ${extra}" title="${rankText(id)} ${suit(id)} · ${Math.floor(id/54)+1}"><b>${rankText(id)}</b><i>${suit(id)}</i><em>${rankText(id)}</em></span>`;
const cards=(list,extra='')=>(list||[]).map(id=>card(id,extra)).join('');
const patternKey=p=>{const key=typeof p==='string'?p:p?.type||p?.kind||'';return ({'triple-single':'tripleSingle','triple-pair':'triplePair','pair-straight':'pairRun','triple-straight':'tripleRun','airplane-single':'airplaneSingle','airplane-pair':'airplanePair','four-two-single':'fourSingles','four-two-pair':'fourPairs',straight_pairs:'pairRun',airplane:'tripleRun',triple_single:'tripleSingle',triple_pair:'triplePair',pair_run:'pairRun',triple_run:'tripleRun',airplane_single:'airplaneSingle',airplane_pair:'airplanePair',four_two_singles:'fourSingles',four_two_pairs:'fourPairs'})[key]||key;};
const labelPattern=p=>t(patternKey(p));
app.innerHTML=`<div class="ambient"></div><header class="topbar"><a class="brand" href="/"><span class="brand-mark">♠</span><span><strong data-i="brand"></strong><small>FLY CIRCUIT ARENA</small></span></a><nav><button class="nav-rule" data-open="rules"><span>?</span><b data-i="rules"></b></button><button id="brain-jump" data-i="brainLive"></button><button data-open="science" data-i="method"></button><a href="https://github.com/tidyBell1912/fly-circuit-arena" target="_blank" rel="noopener" data-i="source"></a></nav><div class="header-tools"><button id="sound-button" aria-pressed="false" title="Sound">♪</button><div class="language-picker"><button id="language-button" aria-haspopup="menu" aria-expanded="false">🇺🇸 ▾</button><div id="language-options" role="menu" hidden>${Object.entries(languages).map(([code,l])=>`<button role="menuitemradio" data-lang="${code}">${l.flag} ${l.name}</button>`).join('')}</div></div></div></header>
<main><section class="hero-line"><div><div class="live-tag"><span id="live-dot"></span><span id="connection"></span></div><h1 data-i="tagline"></h1><p data-i="format"></p></div><div class="season-chips"><div><small data-i="season"></small><strong id="season-number">01</strong></div><div><small data-i="round"></small><strong><span id="round-number">1</span><em>/ 3</em></strong></div><div><small data-i="hand"></small><strong><span id="hand-number">1</span><em>/ 5</em></strong></div></div></section>
<div class="game-layout"><section class="table-column"><div id="table-board" class="table-board"><div class="table-felt"><div class="felt-inner"></div><span class="table-watermark">FLY CARD CLUB</span></div><div class="table-topline"><span id="game-id">#0001</span><span id="stake-info"></span></div><div id="three-loading" data-i="loading3d"></div>
${NAMES.map((name,i)=>`<div class="player-seat seat-${i}" style="--seat-x:${SEATS[i][0]*100}%;--seat-y:${SEATS[i][1]*100}%;--fly-color:${COLORS[i]}" data-seat="${i}"><div class="seat-halo"></div><div class="player-meta"><div class="player-title"><b>${name}</b><span id="count-${i}" class="card-count">20</span></div><span id="role-${i}" class="role-pill"></span><strong class="bean-balance"><i>●</i><span id="balance-${i}">10,000</span></strong><span id="debt-${i}" class="debt-label"></span></div><div id="bubble-${i}" class="move-bubble" hidden></div></div>`).join('')}
<div class="center-play"><div id="phase-pill" class="phase-pill"></div><div id="turn-status" class="turn-status"></div><div id="played-cards" class="played-cards"></div><div id="pattern-label" class="pattern-label"></div><div class="turn-timer"><span id="timer-bar"></span></div><small id="countdown"></small></div><div id="event-splash" class="event-splash" hidden></div><div id="settlement" class="settlement" hidden></div><div class="board-bottom"><div class="bottom-cards"><span data-i="bottom"></span><div id="bottom-cards"></div></div><button id="record-button"><span class="record-dot"></span><span data-i="save"></span></button></div></div>
<div class="hand-inspector"><div class="section-head"><h2 data-i="watchHands"></h2><div id="hand-tabs">${NAMES.map((name,i)=>`<button data-hand="${i}" class="${i===0?'selected':''}" style="--fly-color:${COLORS[i]}">${name}</button>`).join('')}</div></div><div id="hand-cards" class="hand-cards"></div><p data-i="privacy"></p></div>
</section><aside><section class="leaderboard panel"><div class="panel-heading"><span class="heading-icon">♛</span><div><small data-i="roundPoints"></small><h2 data-i="standings"></h2></div><span class="tiny-badge">LIVE</span></div><div id="leaderboard"></div><div class="table-rule" data-i="roundFormat"></div></section><section class="signal-panel panel"><div class="panel-heading"><span class="heading-icon">✧</span><div><small data-i="modeled"></small><h2 data-i="feedback"></h2></div></div><div id="feedback-list"></div><div id="credit-card" class="credit-card"><strong data-i="loan"></strong><p data-i="loanTerms"></p></div></section><section class="table-feed panel"><div class="section-head"><h2 data-i="activity"></h2><span id="total-hands"></span></div><div id="action-feed"></div></section></aside></div>
<section id="brain-lab" class="brain-lab panel"><div class="brain-heading"><div><span class="modal-eyebrow">MALE CNS · LIVE BRAIN ATLAS</span><h2 data-i="brainLive"></h2><p data-i="brainSubtitle"></p></div><button id="record-brain" data-i="save"></button><button id="follow-brain" class="selected" aria-pressed="true" data-i="followPlayer"></button></div><div class="brain-tabs">${NAMES.map((name,i)=>`<button data-brain="${i}" class="${i===0?'selected':''}" style="--fly-color:${COLORS[i]}"><span class="player-dot" style="background:${COLORS[i]}"></span>${name}<small id="brain-decision-${i}">—</small></button>`).join('')}</div><div class="brain-body"><div class="neural-stage"><div id="neural-canvas"></div><div class="neural-stage-top"><b id="neural-owner">Iris</b><span id="neural-record"></span><button id="reset-brain" data-i="resetView"></button></div><div class="neural-view-modes"><button id="brain-whole" class="selected" data-i="wholeBrain"></button><button id="brain-circuit" data-i="selectedCircuit"></button></div><div class="neural-legend"><span style="--dot:#65ccca">PN</span><span style="--dot:#91b9d4">KC</span><span style="--dot:#f59779">MBON</span><span style="--dot:#f1d786">APL</span><span style="--dot:#a48ac4">DAN</span></div><div class="neural-playback"><span data-i="spikeReplay"></span><div><i id="neural-time-bar"></i></div><b id="neural-time">0 / 160 ms</b></div></div><div class="neuron-detail"><small data-i="selectNeuron"></small><form id="neuron-search"><input id="neuron-id-input" aria-label="Neuron ID" inputmode="numeric" placeholder="Neuron ID"><button type="submit" data-i="findNeuron"></button></form><div id="neuron-values"></div><div class="neural-signal"><span data-i="feedback"></span><strong id="neural-feedback">—</strong><small data-i="modeled"></small></div></div></div><p class="brain-footnote"><span data-i="anatomyNote"></span> <a href="https://male-cns.janelia.org/download/" target="_blank" rel="noopener">MaleCNS ↗</a><br><span data-i="neuralAccuracy"></span></p></section><section class="below-table"><div class="onboarding-card"><span class="guide-symbol">♠</span><div><h2 data-i="rules"></h2><p data-i="format"></p></div><button data-open="rules">↗</button></div><div class="onboarding-card"><span class="guide-symbol">⟳</span><div><h2 data-i="initial"></h2><p data-i="reset"></p></div></div></section><section class="archive panel"><div class="section-head"><h2 data-i="archive"></h2><span id="lifetime-stats"></span></div><div id="match-history"></div><div class="section-head season-history-heading"><h2 data-i="pastChampions"></h2></div><div id="season-history"></div></section></main><footer><span data-i="scientific"></span><span data-i="noMoney"></span></footer>
<dialog id="info-dialog"><button class="dialog-close" aria-label="Close">×</button><div id="dialog-content"></div></dialog>`;
function translateLayout(){document.querySelectorAll('[data-i]').forEach(el=>el.textContent=t(el.dataset.i));text('language-button',languages[locale()].flag+' ▾');document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-checked',String(b.dataset.lang===locale())));document.title=t('brand')+' · '+t('format');if(state)render(state);if(selectedNeuron)showNeuron(...selectedNeuron);updateBrain();connectionStatus();}
function connectionStatus(){text('connection',state?.error?t('paused'):connected?t('live'):state?t('reconnecting'):t('connecting'));document.getElementById('live-dot').classList.toggle('online',connected);}
function roleName(i){const role=state?.roles?.[i];return t(role==='landlord'?'landlord':role==='partner'||role==='hidden-landlord'?'partner':role==='farmer'?'farmer':'unknown');}
function render(s){state=s;scene?.update(s);const sea=s.season||{};text('season-number',String(sea.id||1).padStart(2,'0'));text('round-number',sea.round||1);text('hand-number',sea.hand||1);text('game-id','#'+String(s.match.id).padStart(4,'0'));text('stake-info',`${t('base')} ${s.model?.baseStake||100} · ${t('multiplier')} ×${Math.min(16,2**(s.match.bombs||0))}`);text('phase-pill',s.error?t('paused'):t(s.phase));connectionStatus();
 for(let i=0;i<5;i++){text('balance-'+i,n(s.balances?.[i]??s.players?.[i]?.balance??10000));text('debt-'+i,(s.debts?.[i]||0)>0?`${t('debt')} ${n(s.debts[i])}`:'');text('role-'+i,roleName(i));text('count-'+i,s.hands?.[i]?.length??20);const seat=document.querySelector('.seat-'+i);seat.classList.toggle('active',s.turn===i&&['play','bid'].includes(s.phase));seat.classList.toggle('landlord',s.match.landlord===i);seat.classList.toggle('credit-negative',s.credit?.borrowers?.includes(i)&&s.phase==='loanNegative');}
 const action=s.lastAction,playing=s.phase==='play';let message='';if(['play','bid'].includes(s.phase))message=`${NAMES[s.turn]||'…'} · ${t('turn')}`;else if(s.phase==='deal')message=t('format');else if(s.phase.startsWith('loan'))message=(s.credit?.borrowers||[]).map(i=>NAMES[i]).join(' + ')+` · ${s.phase==='loanPositive'?'+5,000':t('creditExplain')}`;else if(s.phase==='settle')message=(s.match.winningSeats||[]).map(i=>NAMES[i]).join(' + ')+' · '+t('teamWin');text('turn-status',message);
 const move=s.tableMove?s.lastPlay:null;html('played-cards',playing&&move?cards(move.cards):s.phase==='deal'?Array.from({length:5},()=>'<span class="card card-back">♠</span>').join(''):'');text('pattern-label',playing&&move?`${NAMES[move.seat]} · ${labelPattern(move.pattern||move.type)}`:'');
 html('bottom-cards',s.bottom?.length?cards(s.bottom,'tiny'):Array.from({length:8},()=>'<span class="card tiny card-back">♠</span>').join(''));
 for(let i=0;i<5;i++){const bubble=document.getElementById('bubble-'+i);const last=(s.match.plays||[]).filter(p=>p.seat===i).at(-1);const show=playing&&last&&(Date.now()+timeOffset-last.at<16000);bubble.hidden=!show;if(show)bubble.textContent=last.pass?t('pass'):labelPattern(last.pattern||last.type);}
 if(action&&action.at!==lastActionAt){lastActionAt=action.at;const key=patternKey(action.pattern);if(key==='bomb'||key==='rocket')splash(t(key),key);else if(s.match.identityRevealedAt===action.at)splash(t('reveal'),'reveal');if(!muted)playSound(key==='bomb'||key==='rocket'?'bomb':'card');document.getElementById('played-cards').classList.remove('dealing');void document.getElementById('played-cards').offsetWidth;document.getElementById('played-cards').classList.add('dealing');}
 const order=sea.standings?.length?sea.standings.map(r=>r.seat):[0,1,2,3,4];
 html('leaderboard',order.map((i,pos)=>`<div class="leader-row"><span class="rank">${pos+1}</span><span class="player-dot" style="background:${COLORS[i]}"></span><div><strong>${NAMES[i]}</strong><small>${t('net')} ${n((s.balances?.[i]??10000)-(s.debts?.[i]||0))}</small><small>${t('winrate')} ${s.stats.matches?(100*s.stats.wins[i]/s.stats.matches).toFixed(1)+'%':'—'}</small></div><b>${sea.scores?.[i]||0}<small>${t('score')}</small></b></div>`).join(''));
 html('feedback-list',NAMES.map((name,i)=>{const f=s.feedback?.[i],delta=f?.delta||0;return `<div class="signal-row"><span>${name}</span><div class="signal-track"><i class="${delta<0?'negative':'positive'}" style="width:${Math.min(48,Math.abs(delta)*35)}%"></i></div><b>${f?(delta>0?'+':'')+delta.toFixed(2):'—'}</b></div>`;}).join(''));
 document.getElementById('credit-card').classList.toggle('warning',s.phase==='loanNegative');text('total-hands',`${n(s.stats?.matches||0)} ${t('hand')}`);const plays=(s.match.plays||[]).slice(-6).reverse();html('action-feed',plays.length?plays.map(p=>`<div class="feed-row"><span class="player-dot" style="background:${COLORS[p.seat]}"></span><strong>${NAMES[p.seat]}</strong><span>${p.pass?t('pass'):labelPattern(p.pattern||p.type)}</span>${p.cards?.length?`<small>${p.cards.length}</small>`:''}</div>`).join(''):`<p class="empty">${t(s.phase)}</p>`);
 renderHand();renderSettlement();if((s.stats?.matches||0)!==lastMatches){lastMatches=s.stats?.matches||0;loadHistory();loadSeasons();}text('lifetime-stats',`${t('allTime')} · ${n(s.stats?.matches||0)}`);
}
async function loadSeasons(){try{const data=await fetch('/api/seasons').then(r=>r.json());html('season-history',data.seasons?.length?data.seasons.slice(0,5).map(s=>`<div class="champion-card"><span>♛</span><div><small>${t('season')} ${s.id}</small><b>${NAMES[s.champion]}</b></div><strong>${s.scores[s.champion]} ${t('score')}</strong></div>`).join(''):`<p class="empty">${t('firstSeason')}</p>`);}catch{}}
function renderHand(){if(!state)return;const hand=[...(state.hands?.[selected]||[])].sort((a,b)=>rank(b)-rank(a)||a-b);html('hand-cards',cards(hand));document.querySelectorAll('[data-hand]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.hand)===selected));}
function renderSettlement(){const el=document.getElementById('settlement'),s=state,visible=['settle','roundEnd','seasonEnd'].includes(s.phase);el.hidden=!visible;if(!visible)return;let title=t(s.phase),names='',content='';if(s.phase==='settle'){names=(s.match.winningSeats||[]).map(i=>NAMES[i]).join(' · ');content=NAMES.map((name,i)=>`<div><span>${name}</span><b class="${(s.match.pointsDelta?.[i]||0)>=0?'gain':'loss'}">${(s.match.pointsDelta?.[i]||0)>0?'+':''}${n(s.match.pointsDelta?.[i]||0)}</b></div>`).join('');}else if(s.phase==='seasonEnd'){names=NAMES[s.season.champion]||'';content=`<p>${t('reset')}</p>`;}else{names=t('net')+' → '+t('score');content=(s.season.standings||[]).map(r=>`<div><span>${NAMES[r.seat]}</span><b>${r.score} ${t('score')}</b></div>`).join('');}html('settlement',`<span class="settlement-symbol">${s.phase==='seasonEnd'?'♛':'✦'}</span><small>${title}</small><h2>${names}</h2><div class="settlement-rows">${content}</div>`);}
function splash(label,kind){const el=document.getElementById('event-splash');el.hidden=false;el.className='event-splash '+kind;el.textContent=label;setTimeout(()=>el.hidden=true,2300);}
let timeOffset=0;
function applyState(s){if(state&&s.createdAt===state.createdAt&&s.revision<state.revision)return;if(!state||s.createdAt!==state.createdAt)neuralCache=Array(5).fill(null);if(s.neuralMode==='delta'){(s.lastNeural||[]).forEach((d,i)=>{if(d)neuralCache[i]=d;});}else if(s.lastNeural)neuralCache=s.lastNeural;s.lastNeural=neuralCache;timeOffset=s.serverTime-Date.now();render(s);updateBrain();}
async function loadState(){try{const r=await fetch('/api/state');if(!r.ok)throw Error();applyState(await r.json());}catch{connectionStatus();}}
function connect(){socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/live`);socket.onopen=()=>{connected=true;retry=1000;connectionStatus();};socket.onmessage=e=>{if(e.data==='pong')return;try{const m=JSON.parse(e.data);if(m.type==='state')applyState(m.data);}catch{}};socket.onclose=()=>{connected=false;connectionStatus();clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connect,retry);retry=Math.min(retry*2,30000);};socket.onerror=()=>socket.close();}
async function loadHistory(){try{const r=await fetch('/api/matches');const {matches}=await r.json();html('match-history',matches.length?matches.slice(0,6).map(m=>`<button class="history-match" data-review="${m.id}"><span>#${String(m.id).padStart(4,'0')}</span><b>${(m.winningSeats||[]).map(i=>NAMES[i]).join(' + ')}</b><small>${m.playCount??m.plays?.length??0} ${t('moves')}</small><em>${t('replay')} ↗</em></button>`).join(''):`<p class="empty">${t('empty')}</p>`);}catch{}}
function playSound(kind){try{audioCtx??=new AudioContext();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.type=kind==='bomb'?'triangle':'sine';o.frequency.setValueAtTime(kind==='bomb'?180:650,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(kind==='bomb'?45:320,audioCtx.currentTime+.14);g.gain.setValueAtTime(.055,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.18);o.start();o.stop(audioCtx.currentTime+.19);}catch{}}
async function openInfo(kind){const dialog=document.getElementById('info-dialog');const c=copy?.[locale()]||copy?.en;if(!c){html('dialog-content',`<h2>${t('rules')}</h2><p>${t('format')}</p><p>${t('roundFormat')}</p><p>${t('loanTerms')}</p>`);}else if(kind==='science'){html('dialog-content',`<span class="modal-eyebrow">MALE CNS · MODEL NOTES</span><h2>${escape(c.scienceTitle)}</h2><p>${escape(c.scienceText)}</p><p>${escape(c.creditNote)}</p><a href="https://github.com/tidyBell1912/fly-circuit-arena/blob/main/docs/doudizhu-protocol.md" target="_blank" rel="noopener">${t('source')}</a>`);}else{html('dialog-content',`<span class="modal-eyebrow">HOW TO PLAY · FIVE PLAYER DOU DIZHU</span><h2>${escape(c.quickTitle)}</h2><p>${escape(c.quickIntro)}</p><ol class="rule-steps">${c.steps.map(x=>`<li>${escape(x)}</li>`).join('')}</ol><div class="pattern-guide">${c.patterns.map(x=>`<div><strong>${escape(x.name)}</strong><p>${escape(x.description)}</p></div>`).join('')}</div><h3>${escape(c.seasonTitle)}</h3><ol class="rule-steps">${c.seasonSteps.map(x=>`<li>${escape(x)}</li>`).join('')}</ol><p class="rules-disclosure">${escape(c.creditNote)}</p>`);}dialog.showModal();}
async function review(id){try{const data=await fetch('/api/matches/'+id).then(r=>r.json()),m=data.match;html('dialog-content',`<span class="modal-eyebrow">${t('replay')} · #${String(id).padStart(4,'0')}</span><h2>${(m.winningSeats||[]).map(i=>NAMES[i]).join(' + ')} · ${t('teamWin')}</h2><div class="review-plays">${m.plays.map((p,j)=>`<div><small>${j+1}</small><b style="color:${COLORS[p.seat]}">${NAMES[p.seat]}</b><div class="review-cards">${p.pass?`<span>${t('pass')}</span>`:cards(p.cards,'tiny')}</div><em>${p.pass?'':labelPattern(p.pattern)}</em></div>`).join('')}</div>`);document.getElementById('info-dialog').showModal();}catch{}}
app.addEventListener('click',e=>{const brain=e.target.closest('[data-brain]'),seat=e.target.closest('[data-seat]');if(brain||seat){neuralSeat=Number(brain?.dataset.brain??seat.dataset.seat);followBrain=false;updateBrain();if(seat)document.getElementById('brain-lab').scrollIntoView({behavior:'smooth',block:'start'});}const lang=e.target.closest('[data-lang]'),hand=e.target.closest('[data-hand]'),open=e.target.closest('[data-open]'),rev=e.target.closest('[data-review]');if(lang){setLanguage(lang.dataset.lang);document.getElementById('language-options').hidden=true;document.getElementById('language-button').setAttribute('aria-expanded','false');}if(hand){selected=Number(hand.dataset.hand);renderHand();}if(open)openInfo(open.dataset.open);if(rev)review(rev.dataset.review);});
document.getElementById('language-button').onclick=()=>{const m=document.getElementById('language-options');m.hidden=!m.hidden;document.getElementById('language-button').setAttribute('aria-expanded',String(!m.hidden));};document.getElementById('brain-jump').onclick=()=>document.getElementById('brain-lab').scrollIntoView({behavior:'smooth',block:'start'});document.getElementById('sound-button').onclick=e=>{muted=!muted;e.currentTarget.setAttribute('aria-pressed',String(!muted));e.currentTarget.classList.toggle('selected',!muted);if(!muted)playSound('card');};document.querySelector('.dialog-close').onclick=()=>document.getElementById('info-dialog').close();document.getElementById('info-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close();});document.addEventListener('click',e=>{if(!e.target.closest('.language-picker'))document.getElementById('language-options').hidden=true;});
window.addEventListener('languagechange',()=>{translateLayout();loadHistory();loadSeasons();});
setInterval(()=>{if(!state)return;const now=Date.now()+timeOffset,remaining=Math.max(0,state.deadline-now);text('countdown',Math.ceil(remaining/1000)+'s');document.getElementById('timer-bar').style.width=`${Math.max(0,Math.min(100,remaining/(state.deadline-state.phaseStart)*100))}%`;},100);
setInterval(()=>{if(socket?.readyState===WebSocket.OPEN)socket.send('ping');},45000);
window.addEventListener('online',()=>{loadState();if(socket?.readyState!==WebSocket.OPEN)connect();});
translateLayout();initLanguage();fetch('/locales/ddz-rules.json').then(r=>r.ok?r.json():null).then(c=>{copy=c;if(location.pathname==='/rules')openInfo('rules');else if(location.pathname==='/methods')openInfo('science');}).catch(()=>{});loadState();connect();createBrainView(document.getElementById('neural-canvas'),showNeuron,(time,count)=>{text('neural-time',`${Math.floor(time)} / 160 ms · ${count}`);document.getElementById('neural-time-bar').style.width=time/160*100+'%';drawBrainRecording(document.querySelector('#neural-canvas canvas'));}).then(v=>{neuralView=v;updateBrain();if(location.pathname==='/brain')document.getElementById('brain-lab').scrollIntoView({block:'start'});}).catch(()=>text('neural-canvas',t('recordUnavailable')));createFlyTable(document.getElementById('table-board'),drawRecording).then(s=>{scene=s;if(state)scene.update(state);document.getElementById('three-loading').hidden=true;}).catch(()=>{text('three-loading','3D unavailable');});
function updateBrain(){if(!state)return;if(followBrain&&state.lastAction?.seat!==undefined)neuralSeat=state.lastAction.seat;document.querySelectorAll('[data-brain]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.brain)===neuralSeat));document.getElementById('follow-brain').classList.toggle('selected',followBrain);document.getElementById('follow-brain').setAttribute('aria-pressed',String(followBrain));neuralCache.forEach((d,i)=>text('brain-decision-'+i,d?'#'+d.decisionNumber:'—'));text('neural-owner',NAMES[neuralSeat]);const data=neuralCache[neuralSeat];text('neural-record',data?`${t('latestDecision')} #${data.decisionNumber} · ${new Date(data.at).toLocaleTimeString(locale(),{hour12:false})}`:t('waitingNeural'));const f=state.feedback?.[neuralSeat];text('neural-feedback',f?(f.delta>0?'+':'')+f.delta.toFixed(2):'—');neuralView?.update(data);}
function showNeuron(node,row,record){selectedNeuron=[node,row,record];const id=node.id,role=node.role;if(document.activeElement!==document.getElementById('neuron-id-input'))document.getElementById('neuron-id-input').value=id;html('neuron-values',`<div class="neuron-identity"><span>${role}</span><strong>${id}</strong></div>${!row?`<p class="neuron-note">${record?t('anatomyOnly'):t('waitingNeural')}</p>`:`<dl><div><dt>${t('spikeCount')}</dt><dd>${row[2]===null?'—':row[2]}</dd></div><div><dt>${t('rate')}</dt><dd>${row[3]===null?'—':row[3].toFixed(2)+' Hz'}</dd></div><div><dt>${role==='APL'?t('inhibition'):t('voltage')}</dt><dd>${role==='APL'&&row[5]!==null?Number(row[5]).toFixed(4):row[4]===null?'—':Number(row[4]).toFixed(4)}</dd></div></dl><p class="neuron-note">${role==='PN'?t('noVoltage'):t('modelUnits')}</p>`}`);}
document.getElementById('follow-brain').onclick=()=>{followBrain=!followBrain;updateBrain();};document.getElementById('reset-brain').onclick=()=>{neuralView?.reset();brainMode(false);};const brainMode=focus=>{neuralView?.focusCircuit(focus);document.getElementById('brain-whole').classList.toggle('selected',!focus);document.getElementById('brain-circuit').classList.toggle('selected',focus);};document.getElementById('brain-whole').onclick=()=>brainMode(false);document.getElementById('brain-circuit').onclick=()=>brainMode(true);document.getElementById('neuron-search').onsubmit=e=>{e.preventDefault();const found=neuralView?.inspect(document.getElementById('neuron-id-input').value);if(!found)html('neuron-values',`<p class="neuron-note">${t('neuronMissing')}</p>`);};
const recordingBackground=new Image();recordingBackground.src='/art/ddz/teahouse.png';
function drawRecording(flyCanvas){
 if(!recording||recording.kind!=='table'||!state)return;const {canvas,ctx:c,start}=recording,w=1280,h=900;c.fillStyle='#112c2c';c.fillRect(0,0,w,h);if(recordingBackground.complete)c.drawImage(recordingBackground,0,0,w,h);c.fillStyle='#072c2c99';c.fillRect(0,0,w,h);
 c.save();c.translate(w/2,405);c.beginPath();c.ellipse(0,0,465,235,0,0,Math.PI*2);c.fillStyle='#28644f';c.fill();c.lineWidth=15;c.strokeStyle='#b78648';c.stroke();c.lineWidth=2;c.strokeStyle='#ebd08d';c.stroke();c.restore();c.drawImage(flyCanvas,0,65,w,690);
 c.fillStyle='#071f28db';c.fillRect(0,0,w,72);c.fillStyle='#fce5ae';c.font='800 28px sans-serif';c.fillText(t('brand'),30,43);c.font='15px sans-serif';c.textAlign='right';c.fillText(`${t('season')} ${state.season.id} · ${t('round')} ${state.season.round}/3 · ${t('hand')} ${state.season.hand}/5`,w-30,29);c.fillStyle='#aecfbd';c.font='11px monospace';c.fillText('LIVE / GLOBAL · #'+String(state.match.id).padStart(4,'0'),w-30,52);c.textAlign='left';
 for(let i=0;i<5;i++){const [sx,sy]=SEATS[i],x=sx*w,y=65+sy*690+63;c.fillStyle='#102d2bea';c.fillRect(x-77,y-17,154,57);c.textAlign='center';c.fillStyle=COLORS[i];c.font='700 19px sans-serif';c.fillText(NAMES[i],x,y);c.font='12px sans-serif';c.fillStyle='#f3e2b5';c.fillText(`${roleName(i)} · ${state.hands?.[i]?.length??0} ${t('cards')}`,x,y+17);c.fillStyle='#e4c979';c.fillText(`${n(state.balances[i])} ${t('beans')}`,x,y+33);if(state.debts[i]){c.fillStyle='#cfaff2';c.font='10px sans-serif';c.fillText(`${t('debt')} ${n(state.debts[i])}`,x,y+49);}c.textAlign='left';}
 c.textAlign='center';c.fillStyle='#f5deb0';c.font='600 18px sans-serif';c.fillText(t(state.phase),w/2,332);c.font='14px sans-serif';c.fillText(document.getElementById('turn-status').textContent.slice(0,90),w/2,357);const move=state.tableMove?state.lastPlay:null;const playing=state.phase==='play';
 if(playing&&move){const ids=move.cards||[],step=Math.min(32,510/Math.max(ids.length,1)),startX=w/2-(ids.length*step+20)/2;for(let j=0;j<ids.length;j++){const id=ids[j],x=startX+j*step,y=379;c.fillStyle='#fff4db';c.strokeStyle='#c8a568';c.lineWidth=1;c.beginPath();c.roundRect(x,y,51,76,5);c.fill();c.stroke();c.fillStyle=['♥','♦'].includes(suit(id))||rank(id)===17?'#bd3e35':'#244354';c.font='bold 21px Georgia';c.textAlign='left';c.fillText(rankText(id),x+6,y+23);c.font='16px Georgia';c.fillText(suit(id)==='JOKER'?'★':suit(id),x+6,y+43);}c.textAlign='center';c.fillStyle='#edddac';c.font='12px sans-serif';c.fillText(`${NAMES[move.seat]} · ${labelPattern(move.pattern)}`,w/2,480);}
 if(['settle','seasonEnd','roundEnd'].includes(state.phase)){c.fillStyle='#18392fe6';c.beginPath();c.roundRect(370,370,540,125,18);c.fill();c.strokeStyle='#eed08b';c.stroke();c.fillStyle='#f5d384';c.font='bold 25px sans-serif';c.fillText(state.phase==='seasonEnd'?NAMES[state.season.champion]+' · '+t('champion'):(state.match.winningSeats||[]).map(i=>NAMES[i]).join(' + '),w/2,417);c.font='14px sans-serif';c.fillStyle='#e6dfbb';c.fillText(state.phase==='seasonEnd'?t('reset'):t('teamWin'),w/2,451);}
 c.fillStyle='#10232ddf';c.fillRect(0,796,w,104);c.textAlign='left';c.fillStyle='#e1c582';c.font='15px sans-serif';c.fillText(t('scientific'),30,826);c.fillStyle='#abc1b8';c.font='12px sans-serif';c.fillText(t('noMoney'),30,850);c.font='12px monospace';c.fillText('fly-circuit-arena.fly-circuit-arena.workers.dev',30,877);c.textAlign='right';c.fillStyle='#f1d79d';c.font='14px sans-serif';c.fillText(t('roundPoints')+'   '+NAMES.map((name,i)=>`${name} ${state.season.scores[i]}`).join('   '),w-30,875);c.textAlign='left';
 if(performance.now()-start>=30000){recording.recorder.stop();recording=null;}
}
function drawBrainRecording(brainCanvas){
 if(!recording||recording.kind!=='brain'||!state||!brainCanvas)return;
 const {ctx:c,start}=recording,w=1280,h=900;
 c.fillStyle='#0b2029';c.fillRect(0,0,w,h);c.fillStyle='#f4db9b';c.font='700 32px sans-serif';c.fillText(t('brainLive'),44,58);
 c.fillStyle='#b1c8c8';c.font='14px sans-serif';c.fillText('MALE CNS · '+t('brainSubtitle'),44,87);
 const d=neuralCache[neuralSeat];c.textAlign='right';c.fillStyle=COLORS[neuralSeat];c.font='600 25px sans-serif';c.fillText(NAMES[neuralSeat],w-44,55);c.font='12px sans-serif';c.fillStyle='#b6c9c4';c.fillText(d?`${t('latestDecision')} #${d.decisionNumber}`:t('waitingNeural'),w-44,81);c.textAlign='left';
 const fit=Math.min(1192/brainCanvas.width,584/brainCanvas.height),bw=brainCanvas.width*fit,bh=brainCanvas.height*fit;c.drawImage(brainCanvas,(w-bw)/2,106+(584-bh)/2,bw,bh);
 const row=selectedNeuron?.[1],node=selectedNeuron?.[0];c.fillStyle='#18313a';c.fillRect(32,704,1216,67);c.fillStyle='#eddbab';c.font='17px sans-serif';c.fillText(`${node?.role||'—'} · ${node?.id||'—'}`,52,746);c.font='14px sans-serif';
 if(row){c.fillText(`${t('spikeCount')}: ${row[2]??'—'}`,315,746);c.fillText(`${t('rate')}: ${row[3]===null?'—':row[3].toFixed(2)+' Hz'}`,570,746);c.fillText(`${node.role==='APL'?t('inhibition'):t('voltage')}: ${(node.role==='APL'?row[5]:row[4])??'—'}`,875,746);}
 c.fillStyle='#a5bfbd';c.font='13px sans-serif';c.fillText(t('spikeReplay')+' · '+document.getElementById('neural-time').textContent,44,808);c.font='11px sans-serif';c.fillText(t('neuralAccuracy'),44,835);c.fillStyle='#dec587';c.font='13px monospace';c.fillText('fly-circuit-arena.fly-circuit-arena.workers.dev',44,875);
 if(performance.now()-start>=30000){recording.recorder.stop();recording=null;}
}
let lastClipURL=null;
async function startRecording(kind){
 if(recording||!scene||(kind==='brain'&&!neuralView))return;
 const buttons=[document.getElementById('record-button'),document.getElementById('record-brain')],button=buttons[kind==='brain'?1:0];buttons.forEach(b=>b.disabled=true);button.textContent=t('recording');
 try{
  const canvas=document.createElement('canvas');canvas.width=1280;canvas.height=900;
  const stream=canvas.captureStream(30),mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';
  const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:6000000}),chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
  recorder.onstop=()=>{
   stream.getTracks().forEach(track=>track.stop());neuralView?.setCapturing(false);if(lastClipURL)URL.revokeObjectURL(lastClipURL);
   lastClipURL=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));document.getElementById('clip-download')?.remove();
   const a=document.createElement('a');a.id='clip-download';a.href=lastClipURL;a.download=`fly-doudizhu-${kind}-${locale()}-season-${state.season.id}-hand-${state.match.id}.webm`;a.textContent=t('downloadClip');a.className='clip-download';button.after(a);a.click();
   buttons.forEach(b=>{b.disabled=false;b.textContent=t('save');});
  };
  recording={kind,canvas,ctx:canvas.getContext('2d'),recorder,start:performance.now()};if(kind==='brain')neuralView.setCapturing(true);recorder.start();
 }catch{button.textContent=t('recordUnavailable');buttons.forEach(b=>b.disabled=false);recording=null;neuralView?.setCapturing(false);}
}
document.getElementById('record-button').onclick=()=>startRecording('table');
document.getElementById('record-brain').onclick=()=>startRecording('brain');
